### ISSUE TITLE
There was an error connecting, please check the URL or try again later

### ISSUE THREAD

**Issue by ph08n1x** [acquia/drupal-create#5]
After configuring my Drupal website I managed to get past the error message saying that I have no configured my Drupal website properly. But now it seems when I input my Drupal website, the app will slide to the right, look like it is about to work and then slide back to the error message (display as this issue title).

Any idea what could be going wrong with this? Been trying to fix this for days now...

Update: After copying the configuration details from my drupal garden website, we are now able to connect to our website via the Drupal gardens app BUT NOT with this drupal Create app still. 

What now occurs is after inputting the Drupal URL we get no error message and finally get to the log in screen BUT the app continuously tries to load and after inputting our login details and does not give any error messages now...

**Comment by kylebrowning** [comment]
Which services version are you using?

Trying using Services 3.3

**Comment by jbrauer** [comment]
This is the exact symptoms of https://github.com/acquia/drupal-create/pull/4

Drupal create requires your site have a three part name or makes the URL http://www. and if your site redirects www to non-www it fails silently.

**Comment by weitzman** [comment]
The aforementioned bug was fixed so this issue can likely be closed.
